### YamlMime:BusinessCentralApplicationObject
fqName: System.Environment.Configuration."Advanced Settings"
alId: ID 9202
namespace: System.Environment.Configuration
baseKind: Codeunit
kind: Codeunit
parent: N:Module::System_Application::Namespace::System.Environment.Configuration
langs:
- al
seeAlso:
- '[Codeunit](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-codeunit-object)'
objectProperties:
- name: Access
  value: Public
  promoted: false
- name: InherentEntitlements
  value: X
  promoted: false
- name: InherentPermissions
  value: X
  promoted: false
events:
- syntax:
    signatures:
    - '[IntegrationEvent(False,False)]'
    content: 'internal procedure OnBeforeOpenGeneralSetupExperience(var PageID: Integer, var Handled: Boolean)'
    parameters:
    - id: PageID
      description: The Page ID of the page been invoked.
      parameterType:
        name: Integer
        isExternal: true
    - id: Handled
      description: The flag which if set, would stop executing the OpenGeneralSetupExperience of the assisted setup guide.
      parameterType:
        name: Boolean
        isExternal: true
  summary: Notifies that the Open General Setup Experience has been invoked.
  name: OnBeforeOpenGeneralSetupExperience
  uid: M:Codeunit::System#Environment#Configuration#Advanced_Settings.OnBeforeOpenGeneralSetupExperience(Integer@,Boolean@)
commentId: O:Codeunit::System#Environment#Configuration#Advanced Settings
summary: Advanced settings exposes integration events raised at Advance Settings Page open.
name: '"Advanced Settings"'
uid: O:Codeunit::System#Environment#Configuration#Advanced_Settings
